### PR TITLE
Relax step calculation to allow step to be larger than range span.

### PR DESCRIPTION
**Pull request by kanitw**
Note:
- I have analyzed if making `step` larger than `stop-start` can cause any problem, but I could not find one. 
- This code assumes that `paddingInner < 1`, thus the denominator for the step calculation will never be 0.  (paddingInner = 1 doesn't make sense anyway since bandWidth will be 0.)

### CODE REVIEW

**Comment by jheer** [comment]
I am uncomfortable with the error case when `n == 1 && paddingInner == 1`. The step calc denominator goes to zero and we get a `NaN` pollluting the subsequent calculations. While I agree that in most cases the inner padding should be less than one, I think we should still generate a reasonable, non-erroneous result here. Perhaps a simple special case suffices?

**Comment by kanitw** [comment]
> I am uncomfortable with the error case when `n == 1 && paddingInner == 1`. The step calc denominator goes to zero and we get a `NaN` pollluting the subsequent calculations.

That's true.  

Note that somehow the output visualization still output something despite the NaN pollution when `n == 1 && paddingInner == 1 && paddingOuter == 0`

pasted_image_12_4_16__10_14_am

That said, I agree that NaN pollution is not a good idea.  So I replace the formula with:

```
var space = n - paddingInner + paddingOuter * 2;
step = (stop - start) / (n && space > 0 ? space : 1);
```

(Basically, make the denominator = 1 when space == 0.)

This produces the same visual output as above, but no longer pollutes subsequent calculations with NaN when `n == 1 && paddingInner == 1 && paddingOuter == 0`.

**Comment by kanitw** [comment]
Actually, I tried to update the comment and formula in `vega-encode` to match this and realize that we don't really need `n && ` in the predicate.  (The only problematic case is when space <= 0.)

**Comment by kanitw** [comment]
**correction**
Actually, I tried to update comment **and formula** in vega-encode to match this and realize that we don't really need n && in the predicate. (The only problematic case is **when space <= 0**.)

**Pull request merged**
